### ISSUE TITLE
TO-DO Finalisation

### ISSUE THREAD

**Issue by ArenorRaxx** [Minishellou/minishell#21]
------
##### Assigned to: mcorso

- [x] Manage signals; (merci gaby)

- [x] Fix piping between forks;

- [x] Implement built-ins;

- [x] Investigate pathfinder leaks;

- [x] Implement `$?`;

<br/>

##### Assigned to: gkitoko

- [x] Implement the **quote removal** process; `// May already be implemented in the heredoc proccess, need to be checked`

- [x] Implement `expand_envar_in_string` function;

- [x] Make use of the **Envar Expansion** first and **quote removal** next into the Parsing part;

- [x] Include `'_'` support;

- [x] Do not expand envar in `HEREDOC` arguments;

##### Assigned to: mcorso

- [x] Make use of the **Envar Expansion** into the Heredoc process;
<br/>

##### Assigned to : gkitoko & mcorso

- [x] Incorporate comprehensive error management in :

	- [x] Parsing part;
	
	- [x] Exec part;

Comprehensive error management can be implemented using the `perror()` function inside of atomic functions.
